module.exports = [
  {
    id: "1",
    name: "Pawsitive Foundation",
    address: "503 Broadway",
    city: "Calgary",
    email: "contact@pawsitive.com",
  },
  {
    id: "2",
    name: "Meow Shelter",
    address: "33 Pearl Street SW",
    city: "Calgary",
    email: "contact@meowshelter.com",
  },
  {
    id: "3",
    name: "Happy Cat Foundation",
    address: "300 Main Street",
    city: "Calgary",
    email: "contact@happycatfoundation.com",
  },
  {
    id: "4",
    name: "Kitty Kitty Foundation",
    address: "890 Brannnan Street",
    city: "Edmonton",
    email: "contact@kittykitty.com",
  },
  {
    id: "5",
    name: "Fur Ball Shelter",
    address: "520 Broadway",
    city: "Edmonton",
    email: "contact@furball.com",
  },
  {
    id: "6",
    name: "Smelly Cat Shelter",
    address: "1201 Third Avenue",
    city: "Calgary",
    email: "contact@smellycat.com",
  },
  {
    id: "7",
    name: "Saving Cats Shelter",
    address: "2650 NW 5th Avenue",
    city: "Calgary",
    email: "contact@msavingcats.com",
  },
  {
    id: "8",
    name: "Adopt a Cat Foundation",
    address: "13 SW 1th Avenue",
    city: "Edmonton",
    email: "contact@adoptacat.com",
  },

  {
    id: "9",
    name: "Purr Foundation",
    address: "34 Magazine Avenue",
    city: "Red Deer",
    email: "contact@purrfoundation.com",
  },
  {
    id: "10",
    name: "FurPaws Shelter",
    address: "3 Commercial Avenue",
    city: "Lethbridge",
    email: "contact@furpaws.com",
  },
  {
    id: "11",
    name: "Furever Shelter",
    address: "1800 Heritage Dr SW",
    city: "Medicine Hat",
    email: "contact@furevershelter.com",
  },

  {
    id: "12",
    name: "Purradise Shelter",
    address: "4498 Aviation Way",
    city: "Saint Albert",
    email: "contact@purradiseshelter.com",
  },

  {
    id: "13",
    name: "The Cat’s Shelter",
    address: "2500 Rinehart Road",
    city: "Grande Prairie",
    email: "contact@thecatsshelter.com",
  },
  {
    id: "14",
    name: "Feline Rescue Society",
    address: "1213 Main Street",
    city: "Airdrie",
    email: "contact@felinerescue.com",
  },
  {
    id: "15",
    name: "Cats and the City",
    address: "3242 Gore Street",
    city: "Spruce Grove",
    email: "contact@catsandthecity.com",
  },
  {
    id: "16",
    name: "Catsrose Shelter",
    address: "4500 53 St",
    city: "Leduc",
    email: "contact@catsroseshelter.com",
  },
];
