module.exports = [
  {
    id: "1",
    name: "Lucas",
    username: "lucas",
    password: "lucas",
    email: "lucas@gmail.com",
  },
  {
    id: "2",
    name: "Robson",
    username: "robson",
    password: "robson",
    email: "robson@gmail.com",
  },
  {
    id: "3",
    name: "Carol",
    username: "carol",
    email: "carol@gmail.com",
    password: "carol",
  },
  {
    id: "4",
    name: "Sophia",
    username: "sophia",
    email: "sophia@gmail.com",
    password: "sophia",
  },
  {
    id: "5",
    name: "Bruna",
    username: "bruna",
    email: "bruna@gmail.com",
    password: "bruna",
  },
  {
    id: "6",
    name: "Erica",
    username: "erica",
    email: "Erica@gmail.com",
    password: "erica",
  },
  {
    id: "7",
    name: "Debora",
    username: "debora",
    email: "debora@gmail.com",
    password: "debora",
  },
  {
    id: "8",
    name: "Julia",
    username: "julia",
    email: "julia@gmail.com",
    password: "julia",
  },
  {
    id: "9",
    name: "Bianca",
    username: "bianca",
    email: "bianca@gmail.com",
    password: "bianca",
  },
  {
    id: "10",
    name: "Tamara",
    username: "tamara",
    email: "tamara@gmail.com",
    password: "tamara",
  },
];
